import "./globals.css";
import StoreProvider from "./utils/redux/StoreProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
  title: "Lazendeals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-custom-gradient px-5 h-full  md:px-10 md:py-5">
        <StoreProvider>
          {children}
          <SpeedInsights />
        </StoreProvider>
      </body>
    </html>
  );
}
